export {
  counsellingPath,
  parseCounsellingPath,
  crpPath,
  parseCrpPath,
  dashboardPath,
  parseDashboardPath,
  marketplacePath,
  parseMarketplacePath,
  counsellingAssessmentPath,
  assessmentPath,
  programPageForSlug,
  programPath,
  partnerPath,
  careerPath,
} from './pathRoutes.js';
