/**
 * Unique career / qualification pathways — no Senior/Specialist tier duplicates.
 * Each title appears once. Used by generateCareers.js
 */

const ITI_TRADES = [
  'ITI - Electrician', 'ITI - Fitter', 'ITI - Welder', 'ITI - Turner', 'ITI - Machinist',
  'ITI - Plumber', 'ITI - Carpenter', 'ITI - Mason', 'ITI - Painter', 'ITI - Wireman',
  'ITI - Mechanic (Motor Vehicle)', 'ITI - Electronics Mechanic', 'ITI - Instrument Mechanic',
  'ITI - Information Technology', 'ITI - Computer Operator & Programming Assistant',
  'ITI - Draughtsman (Civil)', 'ITI - Draughtsman (Mechanical)', 'ITI - Surveyor',
  'ITI - Sheet Metal Worker', 'ITI - Tool & Die Maker', 'ITI - Foundryman',
  'ITI - Forger & Heat Treater', 'ITI - Pump Operator-cum-Mechanic',
  'ITI - Lift & Escalator Mechanic', 'ITI - Solar Technician', 'ITI - Architectural Assistant',
  'ITI - Stenographer & Secretarial Assistant', 'ITI - Sewing Technology', 'ITI - Dress Making',
  'ITI - Fashion Design & Technology', 'ITI - Cutting & Sewing', 'ITI - Embroidery & Needle Work',
  'ITI - Hair & Skin Care', 'ITI - Cosmetology', 'ITI - Food Production',
  'ITI - Food & Beverage Service Assistant', 'ITI - Baker & Confectioner', 'ITI - Housekeeper',
  'ITI - Front Office Assistant', 'ITI - Catering & Hospitality Assistant',
  'ITI - Health Sanitary Inspector', 'ITI - Dental Laboratory Equipment Technician',
  'ITI - Plate Maker cum Impositor', 'ITI - Desktop Publishing Operator', 'ITI - Photographer',
  'ITI - Plastic Processing Operator', 'ITI - Rubber Technician', 'ITI - Leather Goods Maker',
  'ITI - Footwear Maker', 'ITI - Spinning Technician', 'ITI - Weaving Technician',
  'ITI - CNC Programming & Operations', 'ITI - Welding & Inspection', 'ITI - Fireman',
  'ITI - Driver cum Mechanic', 'ITI - Marine Fitter', 'ITI - Network Technician',
  'ITI - Maintenance Mechanic', 'ITI - Electrical Maintenance', 'ITI - Agro Processing',
  'ITI - Laboratory Assistant', 'ITI - Civil Engineer Assistant', 'ITI - Plumber & Pipe Fitter',
];

const JOB_ROLES = {
  'Engineering & Technology': [
    'Software Engineer', 'Data Scientist', 'Mechanical Engineer', 'Civil Engineer', 'Electrical Engineer',
    'Electronics Engineer', 'Aerospace Engineer', 'Automobile Engineer', 'Robotics Engineer', 'AI Engineer',
    'Machine Learning Engineer', 'Cloud Architect', 'DevOps Engineer', 'Cybersecurity Analyst', 'Blockchain Developer',
    'Biomedical Engineer', 'Chemical Engineer', 'Petroleum Engineer', 'Mining Engineer', 'Marine Engineer',
    'Nanotechnology Engineer', 'Environmental Engineer', 'Industrial Engineer', 'Metallurgical Engineer',
    'Telecommunications Engineer', 'Embedded Systems Engineer', 'VLSI Design Engineer', 'Structural Engineer',
    'Geotechnical Engineer', 'Production Engineer', 'Quality Assurance Engineer', 'Network Engineer',
    'Full Stack Developer', 'Mobile App Developer', 'Game Developer', 'UI/UX Engineer', 'AR/VR Developer',
    'IoT Engineer', 'Renewable Energy Engineer', 'Nuclear Engineer', 'Agricultural Engineer',
    'Site Reliability Engineer', 'Platform Engineer', 'Firmware Engineer', 'Control Systems Engineer',
    'Hydraulic Engineer', 'Acoustic Engineer', 'Optical Engineer', 'Railway Engineer', 'Highway Engineer',
    'Mechatronics Engineer', 'Instrumentation Engineer', 'Power Systems Engineer', 'RF Engineer',
    'Semiconductor Process Engineer', 'Battery Technology Engineer', 'EV Powertrain Engineer',
    'Geospatial Engineer', 'Water Resources Engineer', 'Tunnel Engineer', 'Bridge Engineer',
    'HVAC Design Engineer', 'Fire Protection Engineer', 'Packaging Engineer', 'Ceramics Engineer',
    'Polymer Engineer', 'Textile Engineer', 'Food Process Engineer', 'Pulp & Paper Engineer',
    'Naval Architect', 'Aeronautical Design Engineer', 'Satellite Systems Engineer',
  ],
  'Medical & Healthcare': [
    'Doctor (MBBS)', 'Surgeon', 'Dentist', 'Physiotherapist', 'Pharmacist', 'Registered Nurse',
    'Veterinarian', 'Ayurvedic Doctor', 'Homeopathic Doctor', 'Occupational Therapist', 'Speech Therapist',
    'Radiologist', 'Pathologist', 'Anesthesiologist', 'Cardiologist', 'Neurologist', 'Pediatrician',
    'Gynecologist', 'Psychiatrist', 'Dermatologist', 'Ophthalmologist', 'ENT Specialist', 'Orthopedic Surgeon',
    'Medical Lab Technologist', 'Clinical Nutritionist', 'Public Health Specialist', 'Epidemiologist',
    'Biomedical Scientist', 'Genetic Counselor', 'Paramedic', 'Dental Hygienist', 'Optometrist',
    'Chiropractor', 'Prosthetist & Orthotist', 'Clinical Psychologist', 'Forensic Medical Examiner',
    'Pulmonologist', 'Nephrologist', 'Oncologist', 'Endocrinologist', 'Rheumatologist',
    'Medical Officer', 'Community Health Worker', 'Hospital Administrator', 'Clinical Research Coordinator',
    'Respiratory Therapist', 'Dialysis Technician', 'Radiology Technician', 'Operation Theatre Technician',
    'Blood Bank Technologist', 'Audiologist', 'Perfusionist', 'Midwife', 'Naturopathy Practitioner',
    'Unani Medicine Practitioner', 'Siddha Medicine Practitioner', 'Yoga Therapist (Clinical)',
    'Sports Medicine Physician', 'Palliative Care Specialist', 'Infectious Disease Specialist',
    'Emergency Medicine Physician', 'Family Medicine Physician', 'Medical Coder', 'Health Informatics Analyst',
  ],
  'Commerce & Finance': [
    'Chartered Accountant', 'Company Secretary', 'Investment Banker', 'Financial Analyst', 'Actuary',
    'Stock Broker', 'Tax Consultant', 'Auditor', 'Cost Accountant', 'Bank Manager', 'Insurance Advisor',
    'Wealth Manager', 'Portfolio Manager', 'Risk Analyst', 'Credit Analyst', 'Loan Officer',
    'Financial Planner', 'Economist', 'Business Analyst', 'Venture Capital Analyst', 'Private Equity Associate',
    'Forensic Accountant', 'Compliance Officer', 'Treasury Manager', 'Mutual Fund Manager',
    'FinTech Specialist', 'Blockchain Finance Analyst', 'GST Consultant', 'Insurance Underwriter',
    'Claims Adjuster', 'Accounts Payable Manager', 'Payroll Specialist', 'Equity Research Analyst',
    'Credit Risk Manager', 'Anti-Money Laundering Analyst', 'Trade Finance Officer', 'Revenue Officer',
    'Statistical Analyst (Finance)', 'Microfinance Officer', 'NBFC Relationship Manager',
    'Securities Compliance Analyst', 'Derivatives Trader', 'Corporate Treasurer', 'Fund Accountant',
  ],
  'Law & Public Service': [
    'Lawyer', 'Judge', 'Legal Advisor', 'Corporate Lawyer', 'Criminal Lawyer', 'Civil Lawyer',
    'Intellectual Property Lawyer', 'Human Rights Lawyer', 'IAS Officer', 'IPS Officer', 'IFS Officer',
    'IRS Officer', 'Public Prosecutor', 'Legal Researcher', 'Notary', 'Mediator', 'Arbitrator',
    'Policy Analyst', 'Diplomat', 'Municipal Commissioner', 'District Collector', 'Civil Services Officer',
    'Railway Officer', 'Bank PO', 'SSC Officer', 'State PSC Officer', 'Tax Law Specialist',
    'Labour Law Consultant', 'Cyber Law Expert', 'Environmental Lawyer', 'Competition Law Specialist',
    'Constitutional Law Expert', 'Family Court Advocate', 'Legal Journalist', 'RTI Activist (Legal)',
    'Public Policy Researcher', 'Urban Governance Officer', 'Rural Development Officer (Govt)',
  ],
  'Science & Research': [
    'Research Scientist', 'Physicist', 'Chemist', 'Biologist', 'Microbiologist', 'Biotechnologist',
    'Geneticist', 'Astronomer', 'Geologist', 'Oceanographer', 'Meteorologist', 'Ecologist',
    'Zoologist', 'Botanist', 'Marine Biologist', 'Forensic Scientist', 'Data Analyst (Science)',
    'Clinical Research Associate', 'Science Writer', 'Patent Examiner', 'Laboratory Manager',
    'Quality Control Scientist', 'Food Scientist', 'Materials Scientist', 'Space Scientist',
    'Immunologist', 'Virologist', 'Toxicologist', 'Seismologist', 'Paleontologist',
    'Computational Biologist', 'Neuroscientist', 'Astrophysicist', 'Crystallographer',
    'Environmental Chemist', 'Soil Chemist', 'Wildlife Biologist', 'Entomologist',
  ],
  'IT & Digital': [
    'Web Developer', 'Digital Marketer', 'SEO Specialist', 'Content Strategist', 'Social Media Manager',
    'Product Manager', 'Scrum Master', 'IT Consultant', 'Database Administrator', 'System Administrator',
    'Technical Writer', 'QA Tester', 'Business Intelligence Analyst', 'ERP Consultant', 'SAP Consultant',
    'Salesforce Administrator', 'Ethical Hacker', 'Penetration Tester', 'Cloud Consultant',
    'Animation Technical Director', 'E-learning Developer', 'CRM Specialist', 'Growth Hacker',
    'Data Engineer', 'Analytics Engineer', 'Site Analytics Specialist', 'No-Code Developer',
    'MLOps Engineer', 'Kubernetes Administrator', 'API Developer', 'Low-Code Platform Developer',
    'IT Service Manager', 'Cyber Forensics Analyst', 'RPA Developer', 'Solutions Architect',
    'Technical Program Manager', 'Release Manager', 'Site Merchandiser (E-commerce)', 'Ad Tech Specialist',
  ],
  'Design & Creative': [
    'Graphic Designer', 'Fashion Designer', 'Interior Designer', 'Architect', 'Animator',
    'Film Director', 'Cinematographer', 'Photographer', 'Illustrator', 'UX Designer', 'UI Designer',
    'Product Designer', 'Jewellery Designer', 'Textile Designer', 'Landscape Architect', 'Urban Planner',
    'Art Director', 'Creative Director', 'Video Editor', 'Sound Engineer', 'Music Producer',
    'Choreographer', 'Theatre Artist', 'Makeup Artist', 'Visual Merchandiser', 'Exhibition Designer',
    'Motion Graphics Designer', '3D Artist', 'Industrial Designer', 'Set Designer',
    'Packaging Designer', 'Character Designer', 'Game Artist', 'Ceramic Artist', 'Calligrapher',
    'Typography Designer', 'Brand Identity Designer', 'Service Designer', 'Design Researcher',
  ],
  'Media & Communication': [
    'Journalist', 'News Anchor', 'Radio Jockey', 'Public Relations Manager', 'Advertising Executive',
    'Copywriter', 'Content Creator', 'YouTuber', 'Podcast Host', 'Editor', 'Publisher',
    'Media Planner', 'Brand Manager', 'Communication Specialist', 'Corporate Trainer',
    'Event Manager', 'Sports Commentator', 'Film Producer', 'Screenwriter', 'Voice Artist',
    'Social Media Influencer', 'Digital PR Specialist', 'Technical Communicator', 'News Producer',
    'Documentary Filmmaker', 'Photojournalist', 'Subtitling Specialist', 'Localization Specialist',
    'Community Manager', 'Crisis Communication Manager', 'Political Campaign Strategist',
  ],
  'Education & Training': [
    'School Teacher', 'University Professor', 'School Principal', 'Education Counselor', 'Academic Coordinator',
    'Curriculum Developer', 'Special Educator', 'Librarian', 'EdTech Content Developer',
    'Coaching Institute Faculty', 'Career Counselor', 'School Administrator', 'Montessori Teacher',
    'Online Tutor', 'Instructional Designer', 'Education Policy Researcher', 'Examination Specialist',
    'Language Trainer', 'Soft Skills Trainer', 'Vocational Trainer', 'STEM Lab Instructor',
    'Early Childhood Educator', 'Adult Literacy Coordinator', 'Education Technology Consultant',
  ],
  'Hospitality & Tourism': [
    'Hotel Manager', 'Executive Chef', 'Pastry Chef', 'Flight Attendant', 'Commercial Pilot',
    'Travel Agent', 'Tour Guide', 'Event Planner', 'Restaurant Manager', 'Cruise Director', 'Sommelier',
    'Housekeeping Manager', 'Front Office Manager', 'Airport Ground Staff', 'Immigration Officer',
    'Tourism Officer', 'Resort Manager', 'Catering Manager', 'Bar Manager', 'Hospitality Consultant',
    'Airline Customer Service Agent', 'Heritage Tourism Guide', 'Spa Manager', 'Banquet Manager',
    'MICE Planner', 'Revenue Manager (Hotels)', 'Guest Relations Executive', 'Food & Beverage Controller',
  ],
  'Agriculture & Environment': [
    'Agricultural Officer', 'Horticulturist', 'Dairy Technologist', 'Fisheries Officer',
    'Forestry Officer', 'Soil Scientist', 'Agronomist', 'Wildlife Conservationist', 'Park Ranger',
    'Environmental Consultant', 'Sustainability Manager', 'Climate Change Analyst', 'Water Resource Manager',
    'Organic Farming Consultant', 'Agri-business Manager', 'Food Safety Officer', 'Veterinary Officer',
    'Aquaculture Specialist', 'Seed Technology Expert', 'Precision Agriculture Specialist',
    'Sericulture Specialist', 'Apiculture Specialist', 'Agri-Input Sales Manager', 'Plant Pathologist',
    'Irrigation Engineer (Agriculture)', 'Carbon Farming Consultant', 'Urban Farmer',
  ],
  'Defence & Security': [
    'Army Officer', 'Navy Officer', 'Air Force Officer', 'NDA Officer', 'Coast Guard Officer',
    'Police Officer', 'CRPF Officer', 'Intelligence Officer', 'Firefighter', 'Security Manager',
    'Private Security Consultant', 'Disaster Management Specialist', 'Border Security Officer',
    'Cyber Crime Investigator', 'Forensic Investigator', 'Anti-Terrorism Specialist',
    'Defence Research Scientist', 'Military Logistics Officer', 'Defence Procurement Officer',
  ],
  'Sports & Fitness': [
    'Professional Athlete', 'Sports Coach', 'Fitness Trainer', 'Yoga Instructor', 'Sports Physiotherapist',
    'Sports Manager', 'Umpire', 'Sports Journalist', 'Nutrition Coach', 'Athletic Trainer',
    'Sports Psychologist', 'Adventure Sports Instructor', 'Physical Education Teacher',
    'Esports Manager', 'Sports Analyst', 'Strength & Conditioning Coach', 'Referee (Professional)',
    'Sports Agent', 'Stadium Operations Manager', 'Sports Marketing Manager',
  ],
  'Business & Management': [
    'Entrepreneur', 'Startup Founder', 'Business Development Manager', 'Operations Manager',
    'HR Manager', 'Marketing Manager', 'Sales Manager', 'Supply Chain Manager', 'Logistics Manager',
    'Retail Manager', 'Franchise Owner', 'Management Consultant', 'Project Manager',
    'Import Export Manager', 'Procurement Manager', 'Customer Success Manager', 'Office Administrator',
    'Store Manager', 'E-commerce Manager', 'Brand Strategist', 'Category Manager', 'Vendor Manager',
    'Quality Manager', 'Facility Manager', 'Change Management Consultant', 'Agile Coach',
    'Chief Sustainability Officer', 'Chief Data Officer', 'Chief Product Officer',
  ],
  'Emerging & Future Careers': [
    'Prompt Engineer', 'Drone Operator', 'EV Technician', 'Green Building Consultant',
    'Carbon Credit Analyst', 'Influencer Marketing Manager', 'Metaverse Developer', 'Quantum Computing Researcher',
    'Space Tourism Coordinator', 'Urban Mobility Planner', 'Digital Ethics Officer', 'Remote Work Consultant',
    'Gig Economy Specialist', 'Creator Economy Manager', 'Bioinformatics Specialist', 'Smart City Planner',
    'AI Ethics Researcher', 'Sustainability Analyst', 'Circular Economy Consultant', 'Health Tech Product Manager',
    'Autonomous Vehicle Test Engineer', 'Vertical Farming Manager', 'Synthetic Biology Technician',
    'Digital Twin Engineer', 'Edge AI Developer', 'Climate Risk Modeler', 'Hydrogen Energy Technician',
    'Space Debris Analyst', 'Neurotechnology Researcher', 'Web3 Community Manager',
  ],
  'Arts & Humanities': [
    'Historian', 'Archaeologist', 'Museum Curator', 'Anthropologist', 'Sociologist',
    'Political Scientist', 'Philosopher', 'Translator', 'Interpreter', 'Foreign Language Teacher',
    'Cultural Program Officer', 'Heritage Conservationist', 'Archivist', 'Social Worker',
    'NGO Program Manager', 'Community Development Officer', 'Rural Development Specialist',
    'Development Studies Researcher', 'Gender Studies Researcher', 'Public Historian',
  ],
  'Trades & Vocational': [
    'Licensed Electrician', 'Licensed Plumber', 'Certified Welder', 'Master Carpenter', 'Automobile Technician',
    'HVAC Technician', 'CNC Operator', 'Tool & Die Maker', 'Refrigeration Technician', 'Solar Panel Installer',
    'Beauty Therapist', 'Hair Stylist', 'Tailor', 'Fashion Stylist', 'Florist',
    'Artisan Baker', 'Butcher', 'Two-Wheeler Mechanic', 'Heavy Equipment Operator', 'Crane Operator',
    'Mobile Phone Repair Technician', 'Laptop Repair Technician', 'CCTV Installation Technician',
    'AC & Refrigeration Repair Technician', 'House Electrician', 'Scaffolder', 'Rigger',
    'Pipe Fitter', 'Industrial Painter', 'Flooring Installer', 'Glazier', 'Locksmith',
    'Elevator Technician', 'Diesel Mechanic', 'Auto Body Repair Technician', 'Tyre Technician',
  ],
};

const BTECH_BRANCHES = [
  'Computer Science & Engineering', 'Information Technology', 'Electronics & Communication Engineering',
  'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering',
  'Biotechnology', 'Aerospace Engineering', 'Automobile Engineering', 'Biomedical Engineering',
  'Petroleum Engineering', 'Mining Engineering', 'Metallurgical Engineering', 'Agricultural Engineering',
  'Food Technology', 'Textile Engineering', 'Environmental Engineering', 'Industrial Engineering',
  'Instrumentation Engineering', 'Marine Engineering', 'Naval Architecture', 'Robotics & Automation',
  'Artificial Intelligence & Data Science', 'Cyber Security', 'Internet of Things',
  'Electronics & VLSI Design', 'Power Engineering', 'Production Engineering', 'Mechatronics',
  'Software Engineering', 'Data Science & Engineering', 'Cloud Computing', 'Geoinformatics',
];

const BSC_PROGRAMS = [
  'Computer Science', 'Information Technology', 'Physics', 'Chemistry', 'Mathematics', 'Statistics',
  'Biotechnology', 'Microbiology', 'Zoology', 'Botany', 'Environmental Science', 'Geology',
  'Electronics', 'Agriculture', 'Horticulture', 'Forestry', 'Home Science', 'Nursing',
  'Radiology & Imaging Technology', 'Medical Laboratory Technology', 'Optometry', 'Forensic Science',
  'Nutrition & Dietetics', 'Animation & Multimedia', 'Fashion & Apparel Design', 'Psychology',
  'Economics', 'Data Science', 'Actuarial Science', 'Aviation', 'Nautical Science',
];

const BCOM_BBA = [
  'B.Com (General)', 'B.Com (Hons) Accounting', 'B.Com Banking & Insurance', 'B.Com Taxation',
  'B.Com Financial Markets', 'BBA (General)', 'BBA Finance', 'BBA Marketing', 'BBA HR',
  'BBA International Business', 'BBA Entrepreneurship', 'BBA Digital Marketing',
  'BBA Aviation Management', 'BBA Hospital Management', 'BBA Retail Management',
  'BBA Logistics & Supply Chain', 'BBA Sports Management', 'BBA Event Management',
];

const BA_PROGRAMS = [
  'BA English Literature', 'BA History', 'BA Political Science', 'BA Sociology', 'BA Psychology',
  'BA Economics', 'BA Geography', 'BA Philosophy', 'BA Journalism & Mass Communication',
  'BA Public Administration', 'BA Fine Arts', 'BA Music', 'BA Dance', 'BA Hindi',
  'BA International Relations', 'BA Social Work', 'BA Rural Development', 'BA Tourism Studies',
  'BA Film Studies', 'BA Linguistics', 'BA Defence & Strategic Studies', 'BA Criminology',
];

const MEDICAL_DEGREES = [
  'MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS', 'BNYS', 'BPT', 'B.Pharm', 'B.Sc Nursing',
  'BMLT (Medical Lab Technology)', 'B.Sc Radiology', 'BOT (Occupational Therapy)', 'B.Sc MLT',
  'MD (General Medicine)', 'MS (General Surgery)', 'MD Pediatrics', 'MD Dermatology',
  'MD Psychiatry', 'MD Radiology', 'MD Anesthesiology', 'MD Pathology', 'MDS Orthodontics',
  'MDS Oral Surgery', 'M.Pharm', 'MPT', 'M.Sc Nursing', 'DNB (Specialty Training)',
];

const DESIGN_DEGREES = [
  'Bachelor of Design (Product)', 'Bachelor of Design (Communication)', 'Bachelor of Design (Fashion)',
  'Bachelor of Design (Interior)', 'Bachelor of Design (Animation)', 'Bachelor of Architecture',
  'Bachelor of Fashion Technology', 'Bachelor of Visual Arts', 'Bachelor of Performing Arts',
  'M.Des Interaction Design', 'M.Des Industrial Design', 'Master of Architecture',
  'Master of Fashion Management', 'PG Diploma in UI/UX Design', 'PG Diploma in Interior Design',
];

const LAW_DEGREES = [
  'BA LLB (Integrated)', 'BBA LLB (Integrated)', 'B.Com LLB (Integrated)', 'LLB (3-year)',
  'LLM (Corporate Law)', 'LLM (Criminal Law)', 'LLM (Constitutional Law)', 'LLM (IP Law)',
];

const DIPLOMA_TOPICS = [
  ['Mechanical Engineering', 'Engineering & Technology'],
  ['Civil Engineering', 'Engineering & Technology'],
  ['Electrical Engineering', 'Engineering & Technology'],
  ['Electronics & Communication', 'Engineering & Technology'],
  ['Computer Engineering', 'Engineering & Technology'],
  ['Automobile Engineering', 'Engineering & Technology'],
  ['Chemical Engineering', 'Engineering & Technology'],
  ['Mining Engineering', 'Engineering & Technology'],
  ['Agricultural Engineering', 'Agriculture & Environment'],
  ['Pharmacy (D.Pharm)', 'Medical & Healthcare'],
  ['Nursing (GNM)', 'Medical & Healthcare'],
  ['Medical Laboratory Technology', 'Medical & Healthcare'],
  ['Radiology & Imaging', 'Medical & Healthcare'],
  ['Operation Theatre Technology', 'Medical & Healthcare'],
  ['Dialysis Technology', 'Medical & Healthcare'],
  ['Optometry', 'Medical & Healthcare'],
  ['Physiotherapy Assistant', 'Medical & Healthcare'],
  ['Hotel Management', 'Hospitality & Tourism'],
  ['Food Production', 'Hospitality & Tourism'],
  ['Travel & Tourism', 'Hospitality & Tourism'],
  ['Airline Cabin Crew', 'Hospitality & Tourism'],
  ['Fashion Designing', 'Design & Creative'],
  ['Interior Designing', 'Design & Creative'],
  ['Graphic Design', 'Design & Creative'],
  ['Animation & VFX', 'Design & Creative'],
  ['Journalism & Mass Communication', 'Media & Communication'],
  ['Digital Marketing', 'IT & Digital'],
  ['Software Development', 'IT & Digital'],
  ['Cyber Security', 'IT & Digital'],
  ['Data Analytics', 'IT & Digital'],
  ['Cloud Computing', 'IT & Digital'],
  ['Accounting & Taxation', 'Commerce & Finance'],
  ['Banking & Finance', 'Commerce & Finance'],
  ['Financial Management', 'Commerce & Finance'],
  ['Business Management', 'Business & Management'],
  ['Human Resource Management', 'Business & Management'],
  ['Supply Chain & Logistics', 'Business & Management'],
  ['Retail Management', 'Business & Management'],
  ['Event Management', 'Hospitality & Tourism'],
  ['Early Childhood Education', 'Education & Training'],
  ['Special Education', 'Education & Training'],
  ['Library & Information Science', 'Education & Training'],
  ['Fire & Safety', 'Defence & Security'],
  ['Industrial Safety', 'Defence & Security'],
  ['Leather Technology', 'Trades & Vocational'],
  ['Plastic Technology', 'Trades & Vocational'],
  ['Tool & Die Making', 'Trades & Vocational'],
  ['Refrigeration & AC', 'Trades & Vocational'],
  ['Solar Technology', 'Trades & Vocational'],
  ['Renewable Energy', 'Agriculture & Environment'],
  ['Horticulture', 'Agriculture & Environment'],
  ['Dairy Technology', 'Agriculture & Environment'],
  ['Fisheries Science', 'Agriculture & Environment'],
  ['Forestry', 'Agriculture & Environment'],
  ['Yoga & Naturopathy', 'Sports & Fitness'],
  ['Sports Coaching', 'Sports & Fitness'],
  ['Criminal Law (Paralegal)', 'Law & Public Service'],
  ['Legal Studies', 'Law & Public Service'],
  ['Social Work', 'Arts & Humanities'],
  ['Rural Development', 'Arts & Humanities'],
  ['Archaeology & Museology', 'Arts & Humanities'],
];

const CERTIFICATE_TOPICS = [
  ['Web Development', 'IT & Digital'],
  ['Python Programming', 'IT & Digital'],
  ['Java Programming', 'IT & Digital'],
  ['Full Stack Development', 'IT & Digital'],
  ['Mobile App Development', 'IT & Digital'],
  ['Data Entry Operator', 'IT & Digital'],
  ['Tally with GST', 'Commerce & Finance'],
  ['Digital Marketing', 'IT & Digital'],
  ['SEO & SEM', 'IT & Digital'],
  ['Graphic Design', 'Design & Creative'],
  ['DTP & Graphic Design', 'Design & Creative'],
  ['Video Editing', 'Media & Communication'],
  ['Videography', 'Media & Communication'],
  ['Photography', 'Design & Creative'],
  ['Makeup Artistry', 'Trades & Vocational'],
  ['Hair Styling', 'Trades & Vocational'],
  ['Nail Art', 'Trades & Vocational'],
  ['Bakery & Confectionery', 'Hospitality & Tourism'],
  ['Food & Beverage Service', 'Hospitality & Tourism'],
  ['Hotel Front Office', 'Hospitality & Tourism'],
  ['Housekeeping', 'Hospitality & Tourism'],
  ['Air Hostess / Cabin Crew Training', 'Hospitality & Tourism'],
  ['Travel & Tourism', 'Hospitality & Tourism'],
  ['Carpentry', 'Trades & Vocational'],
  ['Plumbing', 'Trades & Vocational'],
  ['Electrical House Wiring', 'Trades & Vocational'],
  ['Welding Technology', 'Trades & Vocational'],
  ['Masonry', 'Trades & Vocational'],
  ['Driving & Auto Maintenance', 'Trades & Vocational'],
  ['Two-Wheeler Mechanic', 'Trades & Vocational'],
  ['Laptop & Computer Repairing', 'Trades & Vocational'],
  ['Mobile Phone Repairing', 'Trades & Vocational'],
  ['CCTV Installation', 'Trades & Vocational'],
  ['AC & Refrigeration Repair', 'Trades & Vocational'],
  ['Solar Panel Installation', 'Trades & Vocational'],
  ['Patient Care Assistant', 'Medical & Healthcare'],
  ['General Duty Assistant', 'Medical & Healthcare'],
  ['Home Health Aide', 'Medical & Healthcare'],
  ['Phlebotomy', 'Medical & Healthcare'],
  ['Medical Lab Technician', 'Medical & Healthcare'],
  ['Embroidery', 'Trades & Vocational'],
  ['Tailoring & Dressmaking', 'Trades & Vocational'],
  ['Handloom Weaving', 'Trades & Vocational'],
  ['Floriculture & Gardening', 'Trades & Vocational'],
  ['Beekeeping', 'Agriculture & Environment'],
  ['Mushroom Cultivation', 'Agriculture & Environment'],
  ['Poultry Farming', 'Agriculture & Environment'],
  ['Pottery & Ceramics', 'Design & Creative'],
  ['Stenography', 'Education & Training'],
  ['Office Assistant', 'Business & Management'],
  ['Personality Development', 'Education & Training'],
  ['Computer Applications', 'IT & Digital'],
  ['Apparel Manufacturing', 'Trades & Vocational'],
  ['Cloud Computing (Foundation)', 'IT & Digital'],
  ['Ethical Hacking (Foundation)', 'IT & Digital'],
  ['UI/UX Design (Foundation)', 'Design & Creative'],
  ['Content Writing', 'Media & Communication'],
  ['Stock Market Trading', 'Commerce & Finance'],
  ['GST Practitioner', 'Commerce & Finance'],
  ['Income Tax Practitioner', 'Commerce & Finance'],
];

const BVOC_PROGRAMS = [
  'Software Development', 'Web Technologies', 'Mobile Application Development', 'Data Analytics',
  'Healthcare', 'Food Processing', 'Automobile', 'Logistics', 'Beauty & Wellness',
  'Hospitality Operations', 'Retail Management', 'Banking & Finance', 'Renewable Energy',
  'Agriculture & Allied', 'Fashion Technology', 'Interior Design', 'Animation & Gaming',
];

const MASTERS_PROGRAMS = [
  ['M.Tech Computer Science', 'Engineering & Technology'],
  ['M.Tech Data Science', 'Engineering & Technology'],
  ['M.Tech VLSI Design', 'Engineering & Technology'],
  ['M.Tech Structural Engineering', 'Engineering & Technology'],
  ['M.Tech Thermal Engineering', 'Engineering & Technology'],
  ['M.Tech Environmental Engineering', 'Engineering & Technology'],
  ['MCA (Master of Computer Applications)', 'IT & Digital'],
  ['M.Sc Computer Science', 'Science & Research'],
  ['M.Sc Data Science', 'Science & Research'],
  ['M.Sc Biotechnology', 'Science & Research'],
  ['M.Sc Physics', 'Science & Research'],
  ['M.Sc Chemistry', 'Science & Research'],
  ['M.Com', 'Commerce & Finance'],
  ['MBA (General)', 'Business & Management'],
  ['MBA Finance', 'Business & Management'],
  ['MBA Marketing', 'Business & Management'],
  ['MBA HR', 'Business & Management'],
  ['MBA Operations', 'Business & Management'],
  ['MBA Analytics', 'Business & Management'],
  ['PGDM Finance', 'Commerce & Finance'],
  ['PGDM Marketing', 'Business & Management'],
  ['MA English', 'Arts & Humanities'],
  ['MA History', 'Arts & Humanities'],
  ['MA Political Science', 'Arts & Humanities'],
  ['MA Economics', 'Arts & Humanities'],
  ['MA Journalism', 'Media & Communication'],
  ['MSW (Master of Social Work)', 'Arts & Humanities'],
  ['MPA (Master of Public Administration)', 'Law & Public Service'],
  ['Master of Tourism Administration', 'Hospitality & Tourism'],
  ['Master of Hospital Administration', 'Medical & Healthcare'],
  ['Master of Public Health', 'Medical & Healthcare'],
  ['M.Des Communication Design', 'Design & Creative'],
  ['PhD Computer Science', 'Science & Research'],
  ['PhD Physics', 'Science & Research'],
  ['PhD Management', 'Business & Management'],
  ['PhD Economics', 'Arts & Humanities'],
  ['Integrated B.Tech + M.Tech (CSE)', 'Engineering & Technology'],
  ['Integrated B.Sc + M.Sc (Research)', 'Science & Research'],
  ['Integrated BA + MA (Humanities)', 'Arts & Humanities'],
];

function push(entries, title, category) {
  if (!title || !category) return;
  entries.push({ title: title.trim(), category });
}

/** Build deduplicated career entry list (~1000+ unique pathways) */
export function getAllCareerEntries() {
  const entries = [];
  const seen = new Set();

  const add = (title, category) => {
    const key = title.trim().toLowerCase();
    if (!key || seen.has(key)) return;
    seen.add(key);
    entries.push({ title: title.trim(), category });
  };

  // Job roles (one per title — no Senior/Specialist)
  for (const [category, titles] of Object.entries(JOB_ROLES)) {
    titles.forEach((t) => add(t, category));
  }

  // ITI trades
  ITI_TRADES.forEach((t) => add(t, 'Trades & Vocational'));

  // B.Tech / B.E.
  BTECH_BRANCHES.forEach((b) => add(`B.Tech ${b}`, 'Engineering & Technology'));

  // B.Sc
  BSC_PROGRAMS.forEach((b) => add(`B.Sc ${b}`, 'Science & Research'));

  // B.Com / BBA
  BCOM_BBA.forEach((b) => add(b, 'Commerce & Finance'));

  // BA
  BA_PROGRAMS.forEach((b) => add(b, 'Arts & Humanities'));

  // Medical degrees
  MEDICAL_DEGREES.forEach((d) => add(d, 'Medical & Healthcare'));

  // Design degrees
  DESIGN_DEGREES.forEach((d) => add(d, 'Design & Creative'));

  // Law degrees
  LAW_DEGREES.forEach((d) => add(d, 'Law & Public Service'));

  // Diplomas
  DIPLOMA_TOPICS.forEach(([topic, cat]) => add(`Diploma in ${topic}`, cat));

  // Certificates
  CERTIFICATE_TOPICS.forEach(([topic, cat]) => add(`Certificate in ${topic}`, cat));

  // Bachelor of Vocation
  BVOC_PROGRAMS.forEach((p) => add(`Bachelor of Vocation ${p}`, 'Trades & Vocational'));

  // Masters & integrated
  MASTERS_PROGRAMS.forEach(([title, cat]) => add(title, cat));

  // Professional certifications as pathways
  const PRO_CERTS = [
    ['CA (Chartered Accountancy)', 'Commerce & Finance'],
    ['CS (Company Secretary)', 'Commerce & Finance'],
    ['CMA (Cost & Management Accountancy)', 'Commerce & Finance'],
    ['CFA (Chartered Financial Analyst)', 'Commerce & Finance'],
    ['ACCA (UK Accounting)', 'Commerce & Finance'],
    ['CPA (US Accounting)', 'Commerce & Finance'],
    ['FRM (Financial Risk Manager)', 'Commerce & Finance'],
    ['PMP (Project Management)', 'Business & Management'],
    ['Six Sigma Green Belt', 'Business & Management'],
    ['AWS Solutions Architect Certification', 'IT & Digital'],
    ['Google Cloud Professional Certification', 'IT & Digital'],
    ['Microsoft Azure Administrator Certification', 'IT & Digital'],
    ['Cisco CCNA', 'IT & Digital'],
    ['CompTIA Security+', 'IT & Digital'],
    ['CEH (Certified Ethical Hacker)', 'IT & Digital'],
    ['CISSP', 'IT & Digital'],
    ['NEBOSH Safety Certification', 'Defence & Security'],
    ['NIFT Entrance Pathway (Fashion)', 'Design & Creative'],
    ['NID Entrance Pathway (Design)', 'Design & Creative'],
    ['CEED / UCEED Pathway', 'Design & Creative'],
    ['CLAT Pathway (Law)', 'Law & Public Service'],
    ['UPSC CSE Preparation Pathway', 'Law & Public Service'],
    ['NDA Preparation Pathway', 'Defence & Security'],
    ['NEET UG Preparation Pathway', 'Medical & Healthcare'],
    ['JEE Main & Advanced Pathway', 'Engineering & Technology'],
    ['GATE Preparation Pathway', 'Engineering & Technology'],
    ['CAT / XAT MBA Pathway', 'Business & Management'],
    ['UGC-NET (Research & Lectureship)', 'Education & Training'],
    ['Indian Forest Service (IFoS) Pathway', 'Agriculture & Environment'],
    ['Indian Economic Service Pathway', 'Law & Public Service'],
    ['Indian Statistical Service Pathway', 'Science & Research'],
    ['Merchant Navy (DNS / B.Sc Nautical)', 'Hospitality & Tourism'],
    ['Commercial Pilot License (CPL) Pathway', 'Hospitality & Tourism'],
    ['Aircraft Maintenance Engineer License', 'Engineering & Technology'],
    ['NSQF Level 4 Skill Certification', 'Trades & Vocational'],
    ['NSQF Level 5 Skill Certification', 'Trades & Vocational'],
    ['NSQF Level 6 Skill Certification', 'Trades & Vocational'],
    ['PMKVY Skill Certification', 'Trades & Vocational'],
    ['Apprenticeship (National Apprenticeship Promotion Scheme)', 'Trades & Vocational'],
  ];
  PRO_CERTS.forEach(([t, c]) => add(t, c));

  // Additional unique pathways (batch 2)
  const EXTRA_CERTIFICATES = [
    ['Retail Management', 'Business & Management'],
    ['E-commerce Operations', 'Business & Management'],
    ['Warehouse Management', 'Business & Management'],
    ['Export Documentation', 'Commerce & Finance'],
    ['Import-Export Management', 'Commerce & Finance'],
    ['Railway Apprentice Training', 'Trades & Vocational'],
    ['Loco Pilot Training', 'Trades & Vocational'],
    ['Beautician & Spa Therapy', 'Trades & Vocational'],
    ['Spa Therapy', 'Hospitality & Tourism'],
    ['Barista Training', 'Hospitality & Tourism'],
    ['Tea Tasting & Blending', 'Hospitality & Tourism'],
    ['Chocolate Making', 'Hospitality & Tourism'],
    ['Ice Cream Technology', 'Hospitality & Tourism'],
    ['Nutrition & Dietetics', 'Medical & Healthcare'],
    ['Geriatric Care', 'Medical & Healthcare'],
    ['Dialysis Care Assistant', 'Medical & Healthcare'],
    ['ECG Technician', 'Medical & Healthcare'],
    ['X-Ray Technician', 'Medical & Healthcare'],
    ['Dental Chairside Assistant', 'Medical & Healthcare'],
    ['Veterinary Assistant', 'Agriculture & Environment'],
    ['Dairy Farming', 'Agriculture & Environment'],
    ['Organic Certification', 'Agriculture & Environment'],
    ['GIS & Remote Sensing', 'Science & Research'],
    ['CAD (AutoCAD)', 'Engineering & Technology'],
    ['SolidWorks Design', 'Engineering & Technology'],
    ['Revit Architecture', 'Design & Creative'],
    ['SketchUp 3D Modelling', 'Design & Creative'],
    ['Blender 3D', 'Design & Creative'],
    ['After Effects Motion Graphics', 'Media & Communication'],
    ['Premiere Pro Video Editing', 'Media & Communication'],
    ['Sound Recording', 'Media & Communication'],
    ['Radio Production', 'Media & Communication'],
    ['Podcast Production', 'Media & Communication'],
    ['Translation (Hindi-English)', 'Arts & Humanities'],
    ['Sign Language Interpretation', 'Arts & Humanities'],
    ['Braille Transcription', 'Education & Training'],
    ['Special Needs Education Assistant', 'Education & Training'],
    ['Library Assistant', 'Education & Training'],
    ['Archival Studies', 'Arts & Humanities'],
    ['Museum Studies', 'Arts & Humanities'],
    ['Heritage Walk Guide', 'Arts & Humanities'],
    ['Disaster Response Volunteer', 'Defence & Security'],
    ['First Aid & CPR', 'Medical & Healthcare'],
    ['Lifeguard Certification', 'Sports & Fitness'],
    ['Swimming Coach Certification', 'Sports & Fitness'],
    ['Football Coach (AIFF D-License)', 'Sports & Fitness'],
    ['Cricket Coach (BCCI Level 1)', 'Sports & Fitness'],
    ['Chess Instructor', 'Sports & Fitness'],
    ['Drone Pilot License (DGCA)', 'Emerging & Future Careers'],
    ['GIS Survey Drone Operator', 'Emerging & Future Careers'],
    ['3D Printing Technician', 'Emerging & Future Careers'],
    ['Robotics Technician', 'Emerging & Future Careers'],
    ['EV Battery Technician', 'Emerging & Future Careers'],
    ['EV Charging Station Technician', 'Emerging & Future Careers'],
    ['Smart Home Installation', 'Trades & Vocational'],
    ['IoT Device Installation', 'IT & Digital'],
    ['Fiber Optic Splicing', 'Engineering & Technology'],
    ['Tower Technician (Telecom)', 'Engineering & Technology'],
    ['Substation Technician', 'Engineering & Technology'],
    ['Wind Turbine Technician', 'Engineering & Technology'],
    ['Biogas Plant Operator', 'Agriculture & Environment'],
    ['Water Treatment Plant Operator', 'Engineering & Technology'],
    ['Sewage Treatment Plant Operator', 'Engineering & Technology'],
    ['Fire Safety Officer', 'Defence & Security'],
    ['Industrial Hygiene Officer', 'Defence & Security'],
    ['Occupational Health & Safety', 'Defence & Security'],
  ];
  EXTRA_CERTIFICATES.forEach(([topic, cat]) => add(`Certificate in ${topic}`, cat));

  const EXTRA_DIPLOMAS = [
    ['Mechatronics', 'Engineering & Technology'],
    ['Robotics', 'Engineering & Technology'],
    ['Biomedical Engineering', 'Medical & Healthcare'],
    ['Health Inspector', 'Medical & Healthcare'],
    ['Sanitary Inspector', 'Medical & Healthcare'],
    ['Community Medical Service', 'Medical & Healthcare'],
    ['Ayurvedic Pharmacy', 'Medical & Healthcare'],
    ['Homeopathic Pharmacy', 'Medical & Healthcare'],
    ['Unani Medicine', 'Medical & Healthcare'],
    ['Naturopathy & Yogic Sciences', 'Medical & Healthcare'],
    ['Acupuncture', 'Medical & Healthcare'],
    ['Reflexology', 'Medical & Healthcare'],
    ['Aromatherapy', 'Trades & Vocational'],
    ['Spa Management', 'Hospitality & Tourism'],
    ['Cruise Hospitality', 'Hospitality & Tourism'],
    ['Airport Management', 'Hospitality & Tourism'],
    ['Cargo & Logistics', 'Business & Management'],
    ['Port & Shipping Management', 'Business & Management'],
    ['Customs & Excise', 'Commerce & Finance'],
    ['Economic Statistics', 'Commerce & Finance'],
    ['Actuarial Science', 'Commerce & Finance'],
    ['Insurance & Risk Management', 'Commerce & Finance'],
    ['Co-operative Management', 'Commerce & Finance'],
    ['Rural Banking', 'Commerce & Finance'],
    ['Taxation & GST', 'Commerce & Finance'],
    ['Company Law & Secretarial Practice', 'Law & Public Service'],
    ['Human Rights & Duties', 'Law & Public Service'],
    ['Public Relations', 'Media & Communication'],
    ['Advertising & Brand Communication', 'Media & Communication'],
    ['Film & Television Production', 'Media & Communication'],
    ['Radio & TV Journalism', 'Media & Communication'],
    ['Development Communication', 'Media & Communication'],
    ['Fine Arts', 'Design & Creative'],
    ['Applied Art', 'Design & Creative'],
    ['Sculpture', 'Design & Creative'],
    ['Printmaking', 'Design & Creative'],
    ['Ceramics & Pottery', 'Design & Creative'],
    ['Metal Craft', 'Design & Creative'],
    ['Wood Craft', 'Trades & Vocational'],
    ['Glass Blowing', 'Trades & Vocational'],
    ['Gem & Jewellery Design', 'Design & Creative'],
    ['Diamond Grading', 'Commerce & Finance'],
    ['Fashion Merchandising', 'Design & Creative'],
    ['Textile Design', 'Design & Creative'],
    ['Knitwear Design', 'Design & Creative'],
    ['Footwear Design', 'Design & Creative'],
    ['Leather Technology', 'Trades & Vocational'],
    ['Perfumery & Cosmetics', 'Trades & Vocational'],
    ['Paint Technology', 'Engineering & Technology'],
    ['Surface Coating Technology', 'Engineering & Technology'],
    ['Pulp & Paper Technology', 'Engineering & Technology'],
    ['Sugar Technology', 'Agriculture & Environment'],
    ['Tea Technology', 'Agriculture & Environment'],
    ['Coffee Technology', 'Agriculture & Environment'],
    ['Wine Technology', 'Hospitality & Tourism'],
    ['Brewing Technology', 'Hospitality & Tourism'],
  ];
  EXTRA_DIPLOMAS.forEach(([topic, cat]) => add(`Diploma in ${topic}`, cat));

  const EXTRA_JOB_ROLES = {
    'Engineering & Technology': [
      'Building Information Modelling (BIM) Specialist', 'Computational Fluid Dynamics Analyst',
      'Digital Twin Specialist', 'Additive Manufacturing Engineer', 'Hydrogen Systems Engineer',
      'Smart Grid Engineer', 'Microgrid Engineer', 'Pipeline Engineer', 'Pipeline Integrity Engineer',
      'Corrosion Engineer', 'Reliability Engineer', 'Maintenance Engineer', 'Commissioning Engineer',
      'Field Service Engineer', 'Technical Sales Engineer', 'Patent Engineer', 'Standards Engineer',
    ],
    'Medical & Healthcare': [
      'Sleep Technologist', 'EEG Technologist', 'EMG Technologist', 'Cath Lab Technologist',
      'Cardiac Care Technologist', 'Neurodiagnostic Technologist', 'Stem Cell Technologist',
      'Tissue Bank Technologist', 'Transplant Coordinator', 'Clinical Trial Manager',
      'Pharmacovigilance Associate', 'Regulatory Affairs Specialist', 'Medical Device Specialist',
      'Healthcare Quality Manager', 'Infection Control Nurse', 'Wound Care Specialist',
    ],
    'IT & Digital': [
      'Site Reliability Engineer (SRE)', 'FinOps Engineer', 'Platform Reliability Engineer',
      'Observability Engineer', 'Chaos Engineer', 'Identity & Access Management Specialist',
      'Zero Trust Security Architect', 'Threat Intelligence Analyst', 'SOC Analyst',
      'GRC Analyst', 'Privacy Engineer', 'Data Governance Analyst', 'Master Data Manager',
      'ETL Developer', 'Snowflake Developer', 'Databricks Engineer', 'Tableau Developer',
      'Power BI Developer', 'Looker Developer', 'ServiceNow Developer',
    ],
    'Emerging & Future Careers': [
      'LLM Application Developer', 'AI Product Manager', 'Computer Vision Engineer',
      'NLP Engineer', 'Speech Recognition Engineer', 'Recommender Systems Engineer',
      'Federated Learning Researcher', 'Edge ML Engineer', 'TinyML Engineer',
      'Satellite Data Analyst', 'Geospatial Data Scientist', 'Urban Data Scientist',
      'ESG Reporting Analyst', 'Scope 3 Emissions Analyst', 'Nature Finance Analyst',
      'Regenerative Agriculture Consultant', 'Blue Economy Specialist', 'Ocean Data Analyst',
    ],
    'Agriculture & Environment': [
      'Agri-Drone Pilot', 'Crop Insurance Surveyor', 'Soil Health Card Technician',
      'Post-Harvest Technologist', 'Cold Chain Manager', 'Food Processing Supervisor',
      'Quality Assurance (Food)', 'Halal Certification Auditor', 'Organic Certifier',
      'Watershed Management Officer', 'Wetland Restoration Specialist', 'Mangrove Conservation Officer',
    ],
    'Hospitality & Tourism': [
      'Cloud Kitchen Manager', 'Ghost Kitchen Operator', 'Food Truck Entrepreneur',
      'Dark Store Manager', 'Quick Commerce Operations Lead', 'Airbnb Experience Host',
      'Destination Wedding Planner', 'Adventure Tour Operator', 'Eco-Tourism Guide',
    ],
    'Trades & Vocational': [
      'Heat Pump Installer', 'Biogas Plant Technician', 'Rainwater Harvesting Technician',
      'Greywater Recycling Technician', 'Building Automation Technician', 'BMS Technician',
      'Access Control Technician', 'Fire Alarm Technician', 'Sprinkler System Fitter',
      'Duct Fabricator', 'Insulation Worker', 'Roofer', 'Waterproofing Technician',
    ],
  };
  for (const [category, titles] of Object.entries(EXTRA_JOB_ROLES)) {
    titles.forEach((t) => add(t, category));
  }

  const EXTRA_DEGREES = [
    ['B.Tech Artificial Intelligence & Machine Learning', 'Engineering & Technology'],
    ['B.Tech Blockchain Technology', 'Engineering & Technology'],
    ['B.Tech Smart Manufacturing', 'Engineering & Technology'],
    ['B.Tech Smart Agriculture', 'Agriculture & Environment'],
    ['B.Tech Defence Technology', 'Defence & Security'],
    ['B.Tech Space Technology', 'Engineering & Technology'],
    ['B.Sc Actuarial Science & Quantitative Finance', 'Commerce & Finance'],
    ['B.Sc Forensic Accounting', 'Commerce & Finance'],
    ['B.Sc Clinical Research', 'Medical & Healthcare'],
    ['B.Sc Sports Science', 'Sports & Fitness'],
    ['B.Sc Esports Management', 'Sports & Fitness'],
    ['B.Sc Game Design & Development', 'IT & Digital'],
    ['B.Sc Cyber Forensics', 'IT & Digital'],
    ['B.Sc Geoinformatics', 'Science & Research'],
    ['B.Sc Marine Science', 'Science & Research'],
    ['B.Sc Astrophysics', 'Science & Research'],
    ['B.Sc Nanoscience', 'Science & Research'],
    ['B.Sc Cognitive Science', 'Science & Research'],
    ['B.Sc Environmental Law & Policy', 'Law & Public Service'],
    ['BBA FinTech', 'Commerce & Finance'],
    ['BBA Business Analytics', 'Business & Management'],
    ['BBA Supply Chain Analytics', 'Business & Management'],
    ['BBA Healthcare Management', 'Medical & Healthcare'],
    ['BBA Media Management', 'Media & Communication'],
    ['BBA Real Estate Management', 'Business & Management'],
    ['BA Development Studies', 'Arts & Humanities'],
    ['BA Gender & Development', 'Arts & Humanities'],
    ['BA Peace & Conflict Studies', 'Arts & Humanities'],
    ['BA Museology', 'Arts & Humanities'],
    ['BA Archaeology & Heritage Management', 'Arts & Humanities'],
    ['M.Tech AI & Machine Learning', 'Engineering & Technology'],
    ['M.Tech Cyber Physical Systems', 'Engineering & Technology'],
    ['M.Tech Electric Vehicle Technology', 'Engineering & Technology'],
    ['M.Tech Renewable Energy Systems', 'Engineering & Technology'],
    ['M.Tech Water Resources Engineering', 'Engineering & Technology'],
    ['M.Tech Transportation Engineering', 'Engineering & Technology'],
    ['M.Tech Construction Technology', 'Engineering & Technology'],
    ['M.Tech Geotechnical Engineering', 'Engineering & Technology'],
    ['M.Sc Clinical Psychology', 'Medical & Healthcare'],
    ['M.Sc Counselling Psychology', 'Arts & Humanities'],
    ['M.Sc Forensic Psychology', 'Medical & Healthcare'],
    ['M.Sc Sports Psychology', 'Sports & Fitness'],
    ['M.Sc Environmental Management', 'Agriculture & Environment'],
    ['M.Sc Wildlife Science', 'Agriculture & Environment'],
    ['M.Sc Food Technology', 'Agriculture & Environment'],
    ['M.Sc Nutrition & Dietetics', 'Medical & Healthcare'],
    ['M.Sc Medical Imaging Technology', 'Medical & Healthcare'],
    ['PG Diploma in Clinical Research', 'Medical & Healthcare'],
    ['PG Diploma in Regulatory Affairs', 'Medical & Healthcare'],
    ['PG Diploma in Data Science', 'IT & Digital'],
    ['PG Diploma in Machine Learning', 'IT & Digital'],
    ['PG Diploma in DevOps', 'IT & Digital'],
    ['PG Diploma in Digital Marketing', 'IT & Digital'],
    ['PG Diploma in Brand Management', 'Business & Management'],
    ['PG Diploma in Human Resource Development', 'Business & Management'],
    ['PG Diploma in Public Policy', 'Law & Public Service'],
    ['PG Diploma in Environmental Law', 'Law & Public Service'],
    ['PG Diploma in Film Direction', 'Media & Communication'],
    ['PG Diploma in Screenwriting', 'Media & Communication'],
  ];
  EXTRA_DEGREES.forEach(([title, cat]) => add(title, cat));

  return entries;
}

export function getTargetCareerCount() {
  return getAllCareerEntries().length;
}
